#===================== DO NOT EDIT THIS BLOCK =================================#
import collections
from collections import namedtuple

PASS = "PASS"
TEXT_FORMAT = "text"  # question type when expected answer is a str, int, float, or bool
TEXT_FORMAT_NAMEDTUPLE = "text namedtuple"  # question type when expected answer is a namedtuple
TEXT_FORMAT_UNORDERED_LIST = "text list_unordered"  # question type when the expected answer is a list where the order does *not* matter
TEXT_FORMAT_ORDERED_LIST = "text list_ordered"  # question type when the expected answer is a list where the order does matter
TEXT_FORMAT_ORDERED_LIST_NAMEDTUPLE = "text list_ordered namedtuple"  # question type when the expected answer is a list of namedtuples where the order does matter
TEXT_FORMAT_SPECIAL_ORDERED_LIST = "text list_special_ordered"  # question type when the expected answer is a list where order does matter, but with possible ties. All tied elements are put in a list, where internal order does not matter.
TEXT_FORMAT_DICT = "text dict"  # question type when the expected answer is a dictionary
TEXT_FORMAT_LIST_DICTS_ORDERED = "text list_dicts_ordered"  # question type when the expected answer is a list of dicts where the order does matter
PNG_FORMAT = "png"  # use when the expected answer is an image
HTML_FORMAT = "html"
FILE_FORMAT = "file"
FILE_JSON_FORMAT = "file json"

Question = collections.namedtuple("Question", ["number", "weight", "format"])
#===================== DO NOT EDIT THIS BLOCK =================================#


# EDIT THIS
REQUIRED_FILES = ['mapping.csv', 'movies.csv']


# EDIT THIS
questions = [
    Question(number=1, weight=1, format=TEXT_FORMAT),
    Question(number=2, weight=1, format=TEXT_FORMAT),
    Question(number=3, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=4, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=5, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=6, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=7, weight=1, format=TEXT_FORMAT_DICT),
    Question(number=8, weight=1, format=PNG_FORMAT),
    Question(number=9, weight=1, format=TEXT_FORMAT_DICT),
    Question(number=10, weight=1, format=PNG_FORMAT),
    Question(number=11, weight=1, format=TEXT_FORMAT_DICT),
    Question(number=12, weight=1, format=TEXT_FORMAT_DICT),
    Question(number=13, weight=1, format=PNG_FORMAT),
    Question(number=14, weight=1, format=TEXT_FORMAT_SPECIAL_ORDERED_LIST), # DO NOT check answer by manual lookup of the test file. The answer is stored in a different format here. Run test.py to check if your answer is correct.
    Question(number=15, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=16, weight=1, format=TEXT_FORMAT_LIST_DICTS_ORDERED),
    Question(number=17, weight=1, format=TEXT_FORMAT), # DO NOT check answer by manual lookup of the test file. The answer is stored in a different format here. Run test.py to check if your answer is correct.
    Question(number=18, weight=1, format=TEXT_FORMAT_SPECIAL_ORDERED_LIST), # DO NOT check answer by manual lookup of the test file. The answer is stored in a different format here. Run test.py to check if your answer is correct.
    Question(number=19, weight=1, format=TEXT_FORMAT_SPECIAL_ORDERED_LIST), # DO NOT check answer by manual lookup of the test file. The answer is stored in a different format here. Run test.py to check if your answer is correct.
    Question(number=20, weight=1, format=TEXT_FORMAT_SPECIAL_ORDERED_LIST), # DO NOT check answer by manual lookup of the test file. The answer is stored in a different format here. Run test.py to check if your answer is correct.
]

# EDIT THIS
expected_json = {
      "1": 7.725,
      "2": 6.8,
      "3": [{'title': 'Proud American',
              'year': 2008,
              'genres': ['Drama'],
              'duration': 115,
              'directors': ['Fred Ashman'],
              'actors': ['Michael G. Davis',
               'Cecelia Antoinette',
               'Marie Antoinette',
               'Michelle Ashman'],
              'rating': 1.1},
             {'title': 'Troy: The Resurrection of Aeneas',
              'year': 2018,
              'genres': ['Animation', 'Action', 'Adventure'],
              'duration': 60,
              'directors': ['Aeneas Middleton'],
              'actors': ['Aeneas Middleton', 'Hardley Davidson'],
              'rating': 1.1},
             {'title': 'Browncoats: Independence War',
              'year': 2015,
              'genres': ['Action', 'Sci-Fi', 'War'],
              'duration': 98,
              'directors': ['Francis Hamada'],
              'actors': ['Beth Bemis',
               'Richard Martinsen',
               'Will James Johnson',
               'Nathan Cosmo Rahn'],
              'rating': 1.1},
             {'title': 'The Time Machine (I Found at a Yardsale)',
              'year': 2011,
              'genres': ['Sci-Fi'],
              'duration': 84,
              'directors': ['Steven A. Sandt'],
              'actors': ['George Abdelmalak', 'Steven Ronald Brattman', 'Elise Caloca'],
              'rating': 1.1},
             {'title': 'A Moment of Youth',
              'year': 2011,
              'genres': ['Adventure', 'Biography', 'Comedy'],
              'duration': 143,
              'directors': ['Matthew C. Anderson', 'Nicola Barbour'],
              'actors': ['Isaac Bonillo Alcaina',
               'Gustavo Dettler',
               'Yohanna Farrell-Knight',
               'Luke Heaney'],
              'rating': 1.1}],
      "4": [{'title': 'Avengers: Infinity War',
              'year': 2018,
              'genres': ['Action', 'Adventure', 'Sci-Fi'],
              'duration': 149,
              'directors': ['Anthony Russo', 'Joe Russo'],
              'actors': ['Robert Downey Jr.',
               'Chris Hemsworth',
               'Mark Ruffalo',
               'Chris Evans',
               'Scarlett Johansson'],
              'rating': 8.4},
             {'title': 'Avengers: Endgame',
              'year': 2019,
              'genres': ['Action', 'Adventure', 'Drama'],
              'duration': 181,
              'directors': ['Anthony Russo', 'Joe Russo'],
              'actors': ['Robert Downey Jr.',
               'Chris Evans',
               'Mark Ruffalo',
               'Chris Hemsworth',
               'Scarlett Johansson'],
              'rating': 8.4}],
      "5": [{'title': 'A Kid Like Jake',
              'year': 2018,
              'genres': ['Drama', 'Family'],
              'duration': 92,
              'directors': ['Silas Howard'],
              'actors': ['Claire Danes',
               'Jim Parsons',
               'Octavia Spencer',
               'Priyanka Chopra'],
              'rating': 5.4},
             {'title': 'Hidden Figures',
              'year': 2016,
              'genres': ['Biography', 'Drama', 'History'],
              'duration': 127,
              'directors': ['Theodore Melfi'],
              'actors': ['Taraji P. Henson', 'Octavia Spencer', 'Janelle Monáe'],
              'rating': 7.8},
             {'title': 'The Shape of Water',
              'year': 2017,
              'genres': ['Adventure', 'Drama', 'Fantasy'],
              'duration': 123,
              'directors': ['Guillermo del Toro'],
              'actors': ['Sally Hawkins',
               'Michael Shannon',
               'Richard Jenkins',
               'Octavia Spencer'],
              'rating': 7.3},
             {'title': 'Car Dogs',
              'year': 2016,
              'genres': ['Comedy', 'Drama'],
              'duration': 104,
              'directors': ['Adam Collis'],
              'actors': ['Octavia Spencer',
               'Alessandra Torresani',
               'Patrick J. Adams',
               'Nia Vardalos'],
              'rating': 5.0},
             {'title': 'Small Town Crime',
              'year': 2017,
              'genres': ['Crime', 'Mystery', 'Thriller'],
              'duration': 91,
              'directors': ['Eshom Nelms', 'Ian Nelms'],
              'actors': ['John Hawkes',
               'Anthony Anderson',
               'Octavia Spencer',
               'Robert Forster'],
              'rating': 6.6},
             {'title': 'Instant Family',
              'year': 2018,
              'genres': ['Comedy', 'Drama'],
              'duration': 118,
              'directors': ['Sean Anders'],
              'actors': ['Mark Wahlberg',
               'Rose Byrne',
               'Isabela Merced',
               'Gustavo Escobar',
               'Octavia Spencer'],
              'rating': 7.3},
             {'title': 'The Free World',
              'year': 2016,
              'genres': ['Drama', 'Romance'],
              'duration': 100,
              'directors': ['Jason Lew'],
              'actors': ['Elisabeth Moss',
               'Octavia Spencer',
               'Boyd Holbrook',
               'Sung Kang'],
              'rating': 6.1},
             {'title': 'Being John Malkovich',
              'year': 1999,
              'genres': ['Comedy', 'Drama', 'Fantasy'],
              'duration': 113,
              'directors': ['Spike Jonze'],
              'actors': ['John Cusack', 'Cameron Diaz', 'Ned Bellamy', 'Octavia Spencer'],
              'rating': 7.7},
             {'title': 'Ma',
              'year': 2019,
              'genres': ['Horror', 'Mystery', 'Thriller'],
              'duration': 99,
              'directors': ['Tate Taylor'],
              'actors': ['Octavia Spencer', 'Diana Silvers'],
              'rating': 5.6},
             {'title': 'Luce',
              'year': 2019,
              'genres': ['Drama', 'Mystery'],
              'duration': 109,
              'directors': ['Julius Onah'],
              'actors': ['Naomi Watts', 'Octavia Spencer', 'Kelvin Harrison Jr.'],
              'rating': 6.7},
             {'title': 'Black or White',
              'year': 2014,
              'genres': ['Drama'],
              'duration': 121,
              'directors': ['Mike Binder'],
              'actors': ['Kevin Costner', 'Octavia Spencer', 'Mpho Koaho'],
              'rating': 6.6},
             {'title': 'Fruitvale Station',
              'year': 2013,
              'genres': ['Biography', 'Crime', 'Drama'],
              'duration': 85,
              'directors': ['Ryan Coogler'],
              'actors': ['Michael B. Jordan', 'Melonie Diaz', 'Octavia Spencer'],
              'rating': 7.5},
             {'title': 'The Shack',
              'year': 2017,
              'genres': ['Drama', 'Fantasy'],
              'duration': 132,
              'directors': ['Stuart Hazeldine'],
              'actors': ['Sam Worthington', 'Octavia Spencer', 'Tim McGraw'],
              'rating': 6.3}],
      "6": [{'title': 'Ninja Cheerleaders',
              'year': 2008,
              'genres': ['Action', 'Comedy'],
              'duration': 81,
              'directors': ['David Presley'],
              'actors': ['Trishelle Cannatella',
               'Ginny Weirick',
               'Maitland McConnell',
               'George Takei'],
              'rating': 3.3},
             {'title': 'Live by the Fist',
              'year': 1993,
              'genres': ['Action', 'Crime', 'Drama'],
              'duration': 77,
              'directors': ['Cirio H. Santiago'],
              'actors': ['Jerry Trimble', 'George Takei', 'Ted Markland'],
              'rating': 4.3},
             {'title': 'Free Birds',
              'year': 2013,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 91,
              'directors': ['Jimmy Hayward'],
              'actors': ['Owen Wilson', 'Woody Harrelson', 'Amy Poehler', 'George Takei'],
              'rating': 5.8}],
      "7": {'Action': 5611,
             'Horror': 5175,
             'Sci-Fi': 2148,
             'Crime': 5078,
             'Thriller': 5340,
             'Comedy': 11130,
             'Drama': 16410,
             'Romance': 5753,
             'History': 627,
             'Adventure': 3849,
             'Western': 1177,
             'Family': 1585,
             'Fantasy': 1537,
             'War': 779,
             'Sport': 565,
             'Biography': 1009,
             'Mystery': 2479,
             'Film-Noir': 647,
             'Music': 908,
             'Animation': 676,
             'Musical': 941,
             'Reality-TV': 1,
             'Documentary': 1,
             'News': 1},
      "9": {'1981 to 1990': 2840,
             '2011 to 2020': 8884,
             '2001 to 2010': 6271,
             '1941 to 1950': 2256,
             '1971 to 1980': 1889,
             '1951 to 1960': 2201,
             '1931 to 1940': 2256,
             '1961 to 1970': 1609,
             '1991 to 2000': 4280,
             '1911 to 1920': 120,
             '1921 to 1930': 496},
      "11": {'Action': [{'title': 'The Dark Knight',
               'year': 2008,
               'genres': ['Action', 'Crime', 'Drama'],
               'duration': 152,
               'directors': ['Christopher Nolan'],
               'actors': ['Christian Bale',
                'Heath Ledger',
                'Aaron Eckhart',
                'Michael Caine'],
               'rating': 9.0}],
             'Horror': [{'title': 'Psycho',
               'year': 1960,
               'genres': ['Horror', 'Mystery', 'Thriller'],
               'duration': 109,
               'directors': ['Alfred Hitchcock'],
               'actors': ['Anthony Perkins', 'Vera Miles', 'John Gavin'],
               'rating': 8.5}],
             'Sci-Fi': [{'title': 'Inception',
               'year': 2010,
               'genres': ['Action', 'Adventure', 'Sci-Fi'],
               'duration': 148,
               'directors': ['Christopher Nolan'],
               'actors': ['Leonardo DiCaprio',
                'Joseph Gordon-Levitt',
                'Ellen Page',
                'Tom Hardy'],
               'rating': 8.8}],
             'Crime': [{'title': 'The Godfather',
               'year': 1972,
               'genres': ['Crime', 'Drama'],
               'duration': 175,
               'directors': ['Francis Ford Coppola'],
               'actors': ['Marlon Brando', 'Al Pacino'],
               'rating': 9.2}],
             'Thriller': [{'title': 'The Transcendents',
               'year': 2018,
               'genres': ['Music', 'Mystery', 'Thriller'],
               'duration': 96,
               'directors': ['Derek Ahonen'],
               'actors': ['Rob Franco',
                'Savannah Welch',
                'Kathy Valentine',
                'William Leroy',
                'Derek Ahonen'],
               'rating': 9.2}],
             'Comedy': [{'title': 'The Moving on Phase',
               'year': 2020,
               'genres': ['Comedy'],
               'duration': 85,
               'directors': ['Don Tjernagel'],
               'actors': ['Matt Anderson',
                'Clint Boevers',
                'Jillian Brown',
                'Cody Croskrey',
                'Skott Green'],
               'rating': 9.5}],
             'Drama': [{'title': 'Hopeful Notes',
               'year': 2010,
               'genres': ['Drama'],
               'duration': 94,
               'directors': ['Valerio Zanoli'],
               'actors': ['Walter Nudo', 'Colin Ross', 'Ian Poland'],
               'rating': 9.7}],
             'Romance': [{'title': 'As I Am',
               'year': 2019,
               'genres': ['Drama', 'Fantasy', 'Romance'],
               'duration': 62,
               'directors': ['Anthony Bawn'],
               'actors': ['Andre Myers', 'Jerimiyah Dunbar'],
               'rating': 9.3}],
             'History': [{'title': "Schindler's List",
               'year': 1993,
               'genres': ['Biography', 'Drama', 'History'],
               'duration': 195,
               'directors': ['Steven Spielberg'],
               'actors': ['Liam Neeson',
                'Ben Kingsley',
                'Ralph Fiennes',
                'Caroline Goodall',
                'Jonathan Sagall'],
               'rating': 8.9}],
             'Adventure': [{'title': 'The Lord of the Rings: The Return of the King',
               'year': 2003,
               'genres': ['Action', 'Adventure', 'Drama'],
               'duration': 201,
               'directors': ['Peter Jackson'],
               'actors': ['Sean Astin', 'John Bach', 'Sean Bean', 'Cate Blanchett'],
               'rating': 8.9}],
             'Western': [{'title': "C'era una volta il West",
               'year': 1968,
               'genres': ['Western'],
               'duration': 165,
               'directors': ['Sergio Leone'],
               'actors': ['Claudia Cardinale', 'Henry Fonda', 'Jason Robards'],
               'rating': 8.5}],
             'Family': [{'title': 'All You Can Dream',
               'year': 2012,
               'genres': ['Comedy', 'Drama', 'Family'],
               'duration': 79,
               'directors': ['Valerio Zanoli'],
               'actors': ['Anastacia', 'Hali Mason'],
               'rating': 8.8}],
             'Fantasy': [{'title': 'As I Am',
               'year': 2019,
               'genres': ['Drama', 'Fantasy', 'Romance'],
               'duration': 62,
               'directors': ['Anthony Bawn'],
               'actors': ['Andre Myers', 'Jerimiyah Dunbar'],
               'rating': 9.3}],
             'War': [{'title': 'Saving Private Ryan',
               'year': 1998,
               'genres': ['Drama', 'War'],
               'duration': 169,
               'directors': ['Steven Spielberg'],
               'actors': ['Tom Hanks',
                'Tom Sizemore',
                'Edward Burns',
                'Barry Pepper',
                'Adam Goldberg'],
               'rating': 8.6}],
             'Sport': [{'title': 'The Nomads',
               'year': 2019,
               'genres': ['Drama', 'Sport'],
               'duration': 97,
               'directors': ['Brandon Eric Kamin'],
               'actors': ['Andrea Barnes', 'Erik Blachford', 'Jennifer Butler'],
               'rating': 8.2},
              {'title': 'Raging Bull',
               'year': 1980,
               'genres': ['Biography', 'Drama', 'Sport'],
               'duration': 129,
               'directors': ['Martin Scorsese'],
               'actors': ['Robert De Niro', 'Cathy Moriarty'],
               'rating': 8.2},
              {'title': 'Warrior',
               'year': 2011,
               'genres': ['Action', 'Drama', 'Sport'],
               'duration': 140,
               'directors': ["Gavin O'Connor"],
               'actors': ['Joel Edgerton', 'Tom Hardy', 'Nick Nolte'],
               'rating': 8.2}],
             'Biography': [{'title': "Schindler's List",
               'year': 1993,
               'genres': ['Biography', 'Drama', 'History'],
               'duration': 195,
               'directors': ['Steven Spielberg'],
               'actors': ['Liam Neeson',
                'Ben Kingsley',
                'Ralph Fiennes',
                'Caroline Goodall',
                'Jonathan Sagall'],
               'rating': 8.9}],
             'Mystery': [{'title': 'The Transcendents',
               'year': 2018,
               'genres': ['Music', 'Mystery', 'Thriller'],
               'duration': 96,
               'directors': ['Derek Ahonen'],
               'actors': ['Rob Franco',
                'Savannah Welch',
                'Kathy Valentine',
                'William Leroy',
                'Derek Ahonen'],
               'rating': 9.2}],
             'Film-Noir': [{'title': 'Sunset Blvd.',
               'year': 1950,
               'genres': ['Drama', 'Film-Noir'],
               'duration': 110,
               'directors': ['Billy Wilder'],
               'actors': ['William Holden', 'Gloria Swanson', 'Erich von Stroheim'],
               'rating': 8.4}],
             'Music': [{'title': 'The Transcendents',
               'year': 2018,
               'genres': ['Music', 'Mystery', 'Thriller'],
               'duration': 96,
               'directors': ['Derek Ahonen'],
               'actors': ['Rob Franco',
                'Savannah Welch',
                'Kathy Valentine',
                'William Leroy',
                'Derek Ahonen'],
               'rating': 9.2}],
             'Animation': [{'title': 'Doraleous and Associates',
               'year': 2010,
               'genres': ['Animation'],
               'duration': 100,
               'directors': ['Brent Triplett'],
               'actors': ['Jon Etheridge', 'Bryan Mahoney', 'Nate Panning', 'Tony Schnur'],
               'rating': 8.6}],
             'Musical': [{'title': 'Spies Are Forever',
               'year': 2016,
               'genres': ['Musical'],
               'duration': 159,
               'directors': ['Corey Lubowich'],
               'actors': ['Curt Mega',
                'Mary Kate Wiles',
                'Joey Richter',
                'Brian Rosenthal'],
               'rating': 8.7},
              {'title': "The Guy Who Didn't Like Musicals",
               'year': 2018,
               'genres': ['Comedy', 'Musical'],
               'duration': 112,
               'directors': ['Nick Lang'],
               'actors': ['Jon Matteson', 'Lauren Lopez', 'Joey Richter'],
               'rating': 8.7}],
             'Reality-TV': [{'title': 'Human Zoo',
               'year': 2020,
               'genres': ['Horror', 'Reality-TV', 'Thriller'],
               'duration': 109,
               'directors': ['John E Seymore'],
               'actors': ['Robert Carradine', 'Jose Rosete', 'Rachel Amanda Bryant'],
               'rating': 2.1}],
             'Documentary': [{'title': 'This Is Elvis',
               'year': 1981,
               'genres': ['Documentary', 'Biography', 'Music'],
               'duration': 101,
               'directors': ['Malcolm Leo', 'Andrew Solt'],
               'actors': ['David Scott',
                'Paul Boensch III',
                'Johnny Harra',
                'Larry Raspberry'],
               'rating': 7.5}],
             'News': [{'title': 'A Fighting Season',
               'year': 2015,
               'genres': ['Drama', 'News', 'War'],
               'duration': 82,
               'directors': ['Oden Roberts'],
               'actors': ['Clayne Crawford', 'Lew Temple'],
               'rating': 6.4}]},
      "12": {'Action': 5.5,
             'Horror': 4.6,
             'Sci-Fi': 4.9,
             'Crime': 6.0,
             'Thriller': 5.1,
             'Comedy': 5.9,
             'Drama': 6.1,
             'Romance': 6.2,
             'History': 6.5,
             'Adventure': 6.0,
             'Western': 6.2,
             'Family': 5.9,
             'Fantasy': 5.7,
             'War': 6.4,
             'Sport': 6.1,
             'Biography': 6.7,
             'Mystery': 5.8,
             'Film-Noir': 6.6,
             'Music': 6.2,
             'Animation': 6.4,
             'Musical': 6.2,
             'Reality-TV': 2.1,
             'Documentary': 7.5,
             'News': 6.4},
      "14": ['Documentary',
             'Biography',
             'Film-Noir',
             'History',
             'War',
             'Animation',
             'News',
             'Romance',
             'Western',
             'Music',
             'Musical',
             'Drama',
             'Sport',
             'Crime',
             'Adventure',
             'Comedy',
             'Family',
             'Mystery',
             'Fantasy',
             'Action',
             'Thriller',
             'Sci-Fi',
             'Horror',
             'Reality-TV'],
      "15": [{'title': 'Shrek',
              'year': 2001,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 90,
              'directors': ['Andrew Adamson', 'Vicky Jenson'],
              'actors': ['Mike Myers', 'Eddie Murphy'],
              'rating': 7.8},
             {'title': 'Shrek 2',
              'year': 2004,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 93,
              'directors': ['Andrew Adamson', 'Kelly Asbury'],
              'actors': ['Mike Myers', 'Eddie Murphy'],
              'rating': 7.2},
             {'title': 'Shrek the Third',
              'year': 2007,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 93,
              'directors': ['Chris Miller', 'Raman Hui'],
              'actors': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz', 'Antonio Banderas'],
              'rating': 6.1},
             {'title': 'Shrek Forever After',
              'year': 2010,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 93,
              'directors': ['Mike Mitchell'],
              'actors': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz', 'Antonio Banderas'],
              'rating': 6.3},
             {'title': 'Shrek the Musical',
              'year': 2013,
              'genres': ['Comedy', 'Family', 'Fantasy'],
              'duration': 130,
              'directors': ['Michael John Warren'],
              'actors': ["Brian d'Arcy James", 'Sutton Foster', 'Christopher Sieber'],
              'rating': 7.0},
             {'title': 'Shrek Retold',
              'year': 2018,
              'genres': ['Animation', 'Adventure', 'Comedy'],
              'duration': 90,
              'directors': ['Grant Duffrin'],
              'actors': ['Harry Antonucci', 'Russell Bailey'],
              'rating': 7.5}],
      "16": [{'title': 'Little Man Tate',
              'year': 1991,
              'genres': ['Drama'],
              'duration': 99,
              'directors': ['Jodie Foster'],
              'actors': ['Jodie Foster', 'Alex Lee', 'Adam Hann-Byrd'],
              'rating': 6.6}],
      "17": 'A Perfect World',
      "18": ['Jupiter Ascending', 
             'Speed Racer'],
      "19": ['Hibakusha',
             'King Candy',
             'Amy Winehouse: Fallen Star',
             'Steve Jobs: Visionary Genius',
             'The Road to Hollywood',
             'Danny Greene: The Rise and Fall of the Irishman',
             'From the Manger to the Cross; or, Jesus of Nazareth',
             'Joseph Smith: Prophet of the Restoration',
             'The Trade',
             'Blondes at Work',
             'Spirit of Youth',
             'The Loves of Edgar Allan Poe',
             'Alexander Hamilton',
             'Dillinger',
             'Memoria'],
      "20": ['Audrey Hepburn',
             'Leonardo DiCaprio',
             'Woody Allen',
             'Ryan Gosling',
             'Harold Lloyd',
             'Brad Pitt',
             'Philip Seymour Hoffman',
             'Ralph Fiennes',
             'Laurence Olivier',
             'Groucho Marx',
             'Humphrey Bogart',
             'Amy Adams',
             'Jake Gyllenhaal',
             'Judy Garland',
             'Bette Davis',
             'Albert Brooks',
             'Bill Murray',
             'Russell Crowe',
             'Christian Bale',
             'Buster Keaton',
             'Tom Cruise',
             'Fred Astaire',
             'Chris Cooper',
             'Matt Damon',
             'Donald Crisp'],
    }
